### ISSUE TITLE
North Platte dataset is packaged with winzip.exe - can't extract via command line.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cdss-app-statemod-web#1]
In the "old days", using WinZip was helpful because the installation folder could be defaulted to standard folder like `C:\CDSS\data`.  However, WinZip prevents extracting the file with a command line call or TSTool `UnzipFile` command.  Therefore, a download and install workflow cannot be automated.

It would be better to repackage the dataset as a normal zip file...or figure out if WinZip `exe` file can be run with command line parameters to control, but my initial research did not find a solution without installing `WinZip` software on the computer, and that would defeat the purpose of a self-extracting executable.  There is also some risk that the very old `exe` will not run on current computers, maybe a low risk but still a risk.  And, the installer won't be useful on Linux.

**Comment by macphersonbr** [comment]
Updated and split into StateCU and StateMod datasets. See CDSS website.
