### ISSUE TITLE
CDSS StateMod dataset website would benefit from year for each dataset

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cdss-app-statemod-web#2]
The StateCU datasets have the year of the dataset after the dataset name (e.g., 2015), whereas StateMod do not.   Knowing the year makes it easier to install into the proper folder.  The more detailed dates are useful for versioning but are not often used in zip files so just having the year is helpful.  It would be good if the year could be added on the website. See:

[CDSS StateCU datasets](https://www.colorado.gov/pacific/cdss/consumptive-use-statecu)
[CDSS StateMod datasets](https://www.colorado.gov/pacific/cdss/surface-water-statemod)

**Comment by macphersonbr** [comment]
Made enhancement on CDSS website.
