### ISSUE TITLE
StateCU and StateMod zip files names and install folder are not consistent

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cdss-app-statemod-web#3]
There are variations in zip file names and contents of zip files.  Should they be consistent?  Why did WWG choose different names?  It would be good to make consistent.  Maybe create a table somewhere that lists installer information so consistency can be enforced, such as:

* Installer filename (e.g. `cm2015_StateCU.zip`)
* Dataset name (e.g., `cm2015`)
* Installer top-level folder
    + Do files install into normal data folders like `Diversions`, `StateCU`, `StateMod`, etc.
    + Or is a different top level folder used (such as South Platte folder with date)?
* Is the dataset release date/version included in the installer filename, the dataset folder, or both?

The convention for this repository is that each basin has a folder (e.g., `colorado`) and under that is a date, which allows different versions of the dataset to be released.  However, I have been using the date on the file (e.g., `20151 for `cm2015`) rather than try to sort out the different release dates.

**Comment by macphersonbr** [comment]
All model datasets on CDSS website should be using consistent folder structure and .zip naming convention now.
