### ISSUE TITLE
South Platte dataset packaging is inconsistent with other datasets

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cdss-app-statemod-web#4]
The South Platte downloads unzip into folders that have a date and the folders don't match standard names.  They also don't contain all the supporting folders like "Diversions".  I renamed consistent with the typical folder structure so that the web tools can be consistent but we should discuss whether/how to standardize.

* `SP2016_08312017/` - normally is `StateMod`
* `SP2016_StateCU/` - normally is `StateCU`

I recommend that if version is used, it is handled above the StateMod folder.  I'm adding another issue to this effect.

**Comment by macphersonbr** [comment]
The full South Platte datasets (including folders like "Diversions") are now linked on the CDSS website. There is a StateCU model dataset and a StateMod model dataset.
