### ISSUE TITLE
Inconsistent Docs folder names

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cdss-app-statemod-web#5]
Some datasets have DocsCU and DocsSW, others have DocCU and DocSW.  I don't know if this is by design or an oversight.

It would be good to be consistent in datasets.  In particular, if software is going to assume a name, then there needs to be consistency.

**Comment by macphersonbr** [comment]
Updated all model datasets on CDSS website to "DocsCU" and "DocsSW".
